# Generated by Django 4.2.3 on 2024-03-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_dna_delete_rem'),
    ]

    operations = [
        migrations.CreateModel(
            name='REM',
            fields=[
                ('remid', models.CharField(db_column='REMID', max_length=150, primary_key=True, serialize=False)),
                ('remgeneids', models.CharField(blank=True, db_column='REMGeneIDs', max_length=150, null=True)),
                ('remsymbols', models.CharField(blank=True, db_column='REMSymbols', max_length=150, null=True, verbose_name='REM Symbol(s)')),
                ('remchr', models.CharField(blank=True, db_column='REMChr', max_length=150, null=True)),
                ('remstart', models.IntegerField(blank=True, db_column='REMStart', null=True)),
                ('remend', models.IntegerField(blank=True, db_column='REMEnd', null=True)),
                ('remlength', models.IntegerField(blank=True, db_column='REMLength', null=True)),
            ],
            options={
                'db_table': 'REM',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DNA',
        ),
    ]
