# Generated by Django 4.2.3 on 2024-03-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rem_delete_dna'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rem',
            table='rem',
        ),
        migrations.AlterModelTable(
            name='rna',
            table='rna',
        ),
        migrations.AlterModelTable(
            name='triplexaligner',
            table='triplexaligner',
        ),
    ]
