# Generated by Django 4.2.11 on 2024-04-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_rem_table_alter_rna_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollsChoice',
        ),
        migrations.DeleteModel(
            name='PollsQuestion',
        ),
    ]
