# Generated by Django 4.2.11 on 2024-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_pollschoice_delete_pollsquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dna',
            fields=[
                ('dnaid', models.TextField(blank=True, db_column='DNAID', primary_key=True, serialize=False)),
                ('featureid', models.TextField(blank=True, db_column='FeatureID', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('geneid', models.TextField(blank=True, db_column='GeneID', null=True)),
                ('genesymbol', models.TextField(blank=True, db_column='GeneSymbol', null=True)),
                ('chr', models.TextField(blank=True, db_column='Chr', null=True)),
                ('start', models.TextField(blank=True, db_column='Start', null=True)),
                ('end', models.TextField(blank=True, db_column='End', null=True)),
                ('length', models.TextField(blank=True, db_column='Length', null=True)),
            ],
            options={
                'db_table': 'dna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=300)),
                ('line_num', models.IntegerField(blank=True, null=True)),
                ('end_line_num', models.IntegerField(blank=True, null=True)),
                ('func_name', models.CharField(max_length=300)),
                ('exception_raised', models.BooleanField()),
                ('dynamic', models.BooleanField()),
            ],
            options={
                'db_table': 'silk_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilkProfileQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'silk_profile_queries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilkRequest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=190)),
                ('query_params', models.TextField()),
                ('raw_body', models.TextField()),
                ('body', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('view_name', models.CharField(blank=True, max_length=190, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('encoded_headers', models.TextField()),
                ('meta_time', models.FloatField(blank=True, null=True)),
                ('meta_num_queries', models.IntegerField(blank=True, null=True)),
                ('meta_time_spent_queries', models.FloatField(blank=True, null=True)),
                ('pyprofile', models.TextField()),
                ('num_sql_queries', models.IntegerField()),
                ('prof_file', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'silk_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilkResponse',
            fields=[
                ('status_code', models.IntegerField()),
                ('raw_body', models.TextField()),
                ('body', models.TextField()),
                ('encoded_headers', models.TextField()),
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'silk_response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilkSqlquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('traceback', models.TextField()),
                ('identifier', models.IntegerField()),
                ('analysis', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'silk_sqlquery',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='REM',
        ),
    ]
